version: "3"
services:
  fhir:
    image: "hapiproject/hapi:v5.3.0"
    ports:
      - "8090:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://fhir-db:5432/hapi_r4"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
      hapi.fhir.subscription.resthook_enabled: "true"
      hapi.fhir.subscription.websocket_enabled: "true"
      hapi.fhir.client_id_strategy: "ANY"

  fhir-db:
    image: postgres
    volumes:
      - fhir-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi_r4

volumes:
  fhir-db-data:
